apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
  nodeSelector:
    nonexistent-label: "true"  # Ceci rendra le Pod en état Pending

