# prometheus-alerts.yaml

serverFiles:
  pod-alerts.yaml: 
    groups:
      - name: kubernetes-pod-alerts
        rules:
          - alert: PodNotRunningTooLong
            expr: 
              kube_pod_status_phase{phase="Pending"} > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Pod(s) en Pending depuis plus de 1 minute"
              description: "Un ou plusieurs pods sont en état 'Pending' depuis plus de 1 minute."

