apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-go-app-prod
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-go-app
  template:
    metadata:
      labels:
        app: custom-go-app
    spec:
      containers:
      - name: custom-go-app
        image: custom-go-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085

